server:
  port: 8082

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/snake?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456
  redis:
    host: 127.0.0.1
    port: 6379

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:xml/*Mapper.xml


rocketmq:
  name-server: 106.13.26.49:9876;106.13.26.49:8876
  consumer:
    topic: dancerTopic