server:
  port: 9901

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/snake?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 123456root.
  redis:
    host: 106.13.26.49
    port: 6379
    password: justredis

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:xml/*Mapper.xml


# 未启动xxl项目，关闭配置
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:9630/xxl-job-admin
    executor:
      appname: springboot #xxljob配置的执行器名称，
      ip:
      address:
      port: 9999
      logpath: D:\personalstudy\xxl-job/log/springboot-xxl-job.log
      logretentiondays: 30
    accessToken: default_token


# redisson的配置
clusterServersConfig:
  #连接空闲超时，单位：毫秒
  idleConnectionTimeout: 10000
  #连接超时，单位：毫秒
  connectTimeout: 5000
  #命令等待超时，单位：毫秒
  timeout: 10000
  #命令失败重试次数
  retryAttempts: 5
  #命令重试发送时间间隔，单位：毫秒
  retryInterval: 2000
  #redis集群密码
  password: redisPwd
  #单个连接最大订阅数量
  subscriptionsPerConnection: 5
  #从节点最小空闲连接数
  slaveConnectionMinimumIdleSize: 32
  #从节点连接池大小
  slaveConnectionPoolSize: 64
  #主节点最小空闲连接数
  masterConnectionMinimumIdleSize: 32
  #主节点连接池大小
  masterConnectionPoolSize: 64
  #读取操作的负载均衡模式
  #默认值： SLAVE（只在从服务节点里读取）
  #注：在从服务节点里读取的数据说明已经至少有两个节点保存了该数据，确保了数据的高可用性。
  #设置读取操作选择节点的模式。
  #可用值为：
  #SLAVE - 只在从服务节点里读取。
  #MASTER - 只在主服务节点里读取。
  #MASTER_SLAVE - 在主从服务节点里都可以读取。
  readMode: "SLAVE"
  #节点地址
  nodeAddresses:
    - "redis://108.0.0.112:8000"
    - "redis://108.0.0.113:8000"
    - "redis://108.0.0.114:8000"
    - "redis://108.0.0.115:8000"
    - "redis://108.0.0.116:8000"
    - "redis://108.0.0.117:8000"
  #集群扫描间隔时间
  scanInterval: 1000

